---
name: Get images to Build
description: Get images and variants for building VeneOS
inputs:
  image_flavor:
    description: "Types of Image to Build (veneos, veneos-server)"
    required: true
outputs:
  image:
    description: "List of images that will be built"
    value: ${{ steps.image_match.outputs.image }}
  variants:
    description: "List of variants that will be built"
    value: ${{ steps.variants.outputs.variants }}
runs:
  using: "composite"
  steps:
    - name: Match VeneOS image to base image repo
      id: image_match
      shell: bash
      run: |-
        image=""

        case "${{ inputs.image_flavor }}" in
        "veneos")
          image="ghcr.io/ublue-os/bazzite-gnome"
          ;;
        "veneos-server")
          image="ghcr.io/ublue-os/ucore-hci"
          ;;
        esac

        echo "image=$image" >> "$GITHUB_OUTPUT"
    - name: Variants for VeneOS
      id: variants
      shell: bash
      run: |-
        # Array to Hold Image Names
        case "${{ inputs.image_flavor }}" in
        *)
          variants=("stable" "testing")
          ;;
        esac

        # Make into Json Array
        variants="$(jq --null-input --compact-output '$ARGS.positional' \
        --args "${variants[@]}")"

        # Output
        echo "variants=$variants" >> "$GITHUB_OUTPUT"
